# Generated by Django 3.2.5 on 2022-03-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('do_we_like', models.BooleanField(default=None, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('other_observations', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('leg_number', models.CharField(choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('Other', 'Other')], default='4', max_length=50)),
                ('do_we_like', models.BooleanField(default=None, null=True)),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('owner_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.owner')),
            ],
        ),
    ]
