# Generated by Django 3.2.5 on 2022-03-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220308_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='date_of_birth',
        ),
    ]
